// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Emitted repeatedly to `"ai://download-progress"` while [`ai_download_model`]
 * runs, so the settings screen can show real progress instead of an
 * indeterminate spinner for what is, on an ordinary connection, a
 * multi-minute wait for the ~350&nbsp;MB model file.
 */
export type AiDownloadProgress = { file_name: string, bytes_downloaded: number, total_bytes: number, };
