// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AiStatus = { enabled_in_settings: boolean, model_downloaded: boolean, model_name: string, engine_running: boolean, };
