// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppSettings = { auto_lock_minutes: number, clipboard_clear_seconds: number, 
/**
 * Whether the local AI subsystem may run at all. Defaults to `false` --
 * AI is opt-in, never a silent default, matching specification section
 * 2's "Local AI = OFF must leave every vault feature working." Turning
 * this off does not just hide the UI; `ai.rs` refuses every AI command
 * while it is false, so a stale cached frontend state can't route
 * around the setting.
 */
ai_enabled: boolean, };
