// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppSettings = { auto_lock_minutes: number, clipboard_clear_seconds: number, 
/**
 * Sync with paired devices in the background while the vault is
 * unlocked and the app is open, instead of only when "Sync now" is
 * pressed. On by default: two paired devices that are both open should
 * simply agree. A settings file from an older build (which has no such
 * key, and may still carry the removed `ai_enabled` flag -- serde ignores
 * unknown keys) gets the default.
 */
auto_sync: boolean, };
