// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SecretKind } from "./SecretKind";

/**
 * What the classify command returns to the UI: the recognised kind and, when
 * the rules name one, the service it belongs to.
 */
export type Classification = { kind: SecretKind, provider: string | null, };
