// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SecretKind } from "./SecretKind";

export type ClassificationOutput = { kind: SecretKind, provider: string | null, confidence: number, };
