// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SecretRecord } from "./SecretRecord";

/**
 * The decrypted losing side of a genuine concurrent edit (INV-109), paired
 * with the id needed to act on it -- see [`Vault::list_conflicts`].
 */
export type ConflictSummary = { conflict_id: string, record: SecretRecord, };
