// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SecretKind } from "./SecretKind";

/**
 * A high-confidence classification. `provider` is a short, stable string
 * suitable for display and for [`crate::ai::gateway::AiGateway::suggest_name`]'s
 * input -- never inferred, only ever a literal match on a known prefix.
 */
export type DeterministicMatch = { kind: SecretKind, provider: string | null, };
