// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiscoveredPeer = { device_id: string, fingerprint_hex: string, addresses: Array<string>, port: number, };
