// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvNameEntry } from "./EnvNameEntry";

export type EnvNameClassificationOutput = { names: Array<EnvNameEntry>, };
