// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvNameEntry } from "./EnvNameEntry";

/**
 * `names` defaults to empty for the same reason `SearchFilterOutput`'s
 * fields do: a model that returns `{}` has found nothing, which is a
 * legitimate answer, not a malformed response worth failing the whole
 * import over. `deny_unknown_fields` still rejects anything *extra*.
 */
export type EnvNameClassificationOutput = { names: Array<EnvNameEntry>, };
