// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtractedField } from "./ExtractedField";

/**
 * See [`EnvNameClassificationOutput`] -- `fields` defaults to empty so "the
 * model found nothing" reads as an empty result the UI can explain, not as
 * a parse failure the user sees as a generic error.
 */
export type ExtractedFieldsOutput = { fields: Array<ExtractedField>, };
