// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RustEnvironment } from "./RustEnvironment";
import type { SecretPayload } from "./SecretPayload";

/**
 * What a caller supplies to create a record. Timestamps and id are assigned
 * by the vault, never by the caller.
 */
export type NewSecret = { name: string, project: string, environment: RustEnvironment, payload: SecretPayload, notes?: string | null, tags: Array<string>, provider?: string | null, };
