// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OwnIdentity = { device_id: string, fingerprint_display: string, fingerprint_hex: string, };
