// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PairingHostStarted = { address: string, port: number, code: string | null, device_id: string, fingerprint_display: string, };
