// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PairingSasReady = { sas: string, peer_device_id: string, peer_fingerprint_display: string, };
