// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Deployment environment. `Unassigned` is a first-class value rather than an
 * `Option`, because "this credential has no environment" is a state the
 * cleanup assistant reports on, not missing data.
 */
export type RustEnvironment = "Development" | "Staging" | "Production" | "Unassigned";
