// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RustEnvironment } from "./RustEnvironment";
import type { SecretKind } from "./SecretKind";

export type SearchFilterOutput = { project: string | null, environment: RustEnvironment | null, kind: SecretKind | null, tags: Array<string>, text: string | null, };
