// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RustEnvironment } from "./RustEnvironment";
import type { SecretKind } from "./SecretKind";

/**
 * The structured part of a search query. Every field is optional: a query
 * that names only an environment leaves the rest empty.
 */
export type SearchFilter = { project?: string | null, environment?: RustEnvironment | null, kind?: SecretKind | null, tags: Array<string>, text?: string | null, };
