// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RustEnvironment } from "./RustEnvironment";
import type { SecretPayload } from "./SecretPayload";

/**
 * A partial update. `None` means "leave unchanged", which is why every field
 * is an `Option` even where the underlying field is already optional.
 *
 * Every field is `#[ts(optional...)]`: `apps/ui/src/lib/vault-repository.ts`
 * builds this from `const update: ipc.SecretUpdate = {}` and assigns fields
 * incrementally, so the generated TS type must accept an empty object --
 * unlike `#[serde(default)]` alone, which only affects deserialization
 * leniency and (per ts-rs's serde-compat) does not by itself make a field
 * optional in the generated type.
 */
export type SecretUpdate = { name?: string, project?: string, environment?: RustEnvironment, payload?: SecretPayload, notes?: string | null, tags?: Array<string>, provider?: string | null, 
/**
 * Set true to stamp the rotation date as now.
 */
mark_rotated?: boolean, };
