// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RustEnvironment } from "./RustEnvironment";
import type { SecretPayload } from "./SecretPayload";

/**
 * A partial update. `None` means "leave unchanged", which is why every field
 * is an `Option` even where the underlying field is already optional.
 *
 * Every field is `#[ts(optional...)]`: `apps/ui/src/lib/vault-repository.ts`
 * builds this from `const update: ipc.SecretUpdate = {}` and assigns fields
 * incrementally, so the generated TS type must accept an empty object --
 * unlike `#[serde(default)]` alone, which only affects deserialization
 * leniency and (per ts-rs's serde-compat) does not by itself make a field
 * optional in the generated type.
 */
export type SecretUpdate = { name?: string, project?: string, environment?: RustEnvironment, payload?: SecretPayload, notes?: string | null, tags?: Array<string>, provider?: string | null, 
/**
 * Set true to stamp the rotation date as now.
 */
mark_rotated?: boolean, 
/**
 * Change the expiry. `None` (the outer option) leaves it unchanged;
 * `Some(None)` clears it ("does not expire"); `Some(Some(ms))` sets it.
 * The `as`/`optional = nullable` shape matches `notes`/`provider` above:
 * the key may be omitted, and when present may be `null`.
 */
expires_ms?: number | null, };
