// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RustEnvironment } from "./RustEnvironment";
import type { SecretId } from "./SecretId";
import type { SecretPayload } from "./SecretPayload";

/**
 * A full record, secret material included.
 *
 * Never leaves the Rust core in this form except through an explicit reveal.
 */
export type SecretRecord = { id: SecretId, name: string, project: string, environment: RustEnvironment, payload: SecretPayload, notes: string | null, tags: Array<string>, provider: string | null, 
/**
 * Unix milliseconds.
 */
created_ms: number, updated_ms: number, 
/**
 * Last rotation, for the review suggestions in specification section 26.
 */
rotated_ms: number | null, };
