// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kind of credential. Kept in sync with [`SecretPayload`] by
 * [`SecretPayload::kind`]; the UI's form-field map is generated from this.
 */
export type SecretKind = "ApiKey" | "Token" | "EnvVar" | "Database" | "Ssh" | "OAuth" | "Webhook" | "Note" | "Custom";
