// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RustEnvironment } from "./RustEnvironment";
import type { SecretId } from "./SecretId";
import type { SecretKind } from "./SecretKind";

/**
 * Everything needed to render a record in a list, and nothing more.
 *
 * Structurally incapable of carrying secret material: there is no field for
 * it. `has_notes` is a flag rather than the note text for the same reason --
 * a note can contain a credential (specification section 32).
 */
export type SecretSummary = { id: SecretId, name: string, kind: SecretKind, project: string, environment: RustEnvironment, provider: string | null, tags: Array<string>, has_notes: boolean, created_ms: number, updated_ms: number, rotated_ms: number | null, };
