// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Opaque record identifier. UUIDv7, so ids sort by creation time without
 * carrying a separate sequence column.
 */
export type SecretId = string;
