// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomField } from "./CustomField";

/**
 * The secret material itself.
 *
 * A typed union rather than a flat string, because SSH and database
 * credentials are inherently multi-field. Modelling them as one blob of text
 * pushes parsing into the UI and makes structured import impossible.
 *
 * Every variant zeroizes on drop.
 */
export type SecretPayload = { "kind": "ApiKey", value: string, } | { "kind": "Token", value: string, } | { "kind": "EnvVar", key: string, value: string, } | { "kind": "Database", host: string, port: number, database: string, username: string, password: string, } | { "kind": "Ssh", private_key: string, passphrase: string | null, host: string | null, username: string | null, } | { "kind": "OAuth", client_id: string, client_secret: string, } | { "kind": "Webhook", endpoint: string, secret: string, } | { "kind": "Note", body: string, } | { "kind": "Custom", fields: Array<CustomField>, };
