// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SyncSummary = { records_applied: number, 
/**
 * Genuine concurrent edits detected during this sync (INV-109) -- the
 * losing side of each was preserved, not discarded, but the frontend
 * should surface a non-zero count rather than let it pass silently.
 */
conflicts: number, };
