// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SyncSummary = { 
/**
 * Records this device received and applied.
 */
records_applied: number, 
/**
 * Records this device sent because the peer was missing them. Reported
 * separately so a device that pushed changes does not say "0 updated".
 */
records_sent: number, 
/**
 * Genuine concurrent edits detected during this sync (INV-109) -- the
 * losing side of each was preserved, not discarded, but the frontend
 * should surface a non-zero count rather than let it pass silently.
 */
conflicts: number, };
