// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A paired device this vault will accept a sync connection from.
 *
 * The sealed content -- everything but `device_id` and `fingerprint`, which
 * `sync::transport` needs before the vault's own decryption is relevant.
 * See `docs/CRYPTOGRAPHY.md` section 6 for the fingerprint format.
 */
export type TrustedDevice = { device_id: string, fingerprint_hex: string, name: string, paired_ms: number, last_sync_ms: number | null, };
