// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VaultStatus = { exists: boolean, unlocked: boolean, 
/**
 * Whether this OS build supports a platform key at all -- used to decide
 * whether the settings UI offers the option.
 */
platform_protection_available: boolean, 
/**
 * Whether *this* vault currently has the platform slot set up. Readable
 * while locked, since it decides whether the unlock screen should offer
 * "unlock with this Windows account" before anything has been typed.
 */
platform_protection_enabled: boolean, 
/**
 * Whether Windows Hello for Apps is available on this machine
 * (hardware plus an enrolled biometric/PIN) -- used to decide whether
 * Settings offers the Hello-gate option at all. Not the same question
 * as `platform_protection_available`: a machine can have DPAPI (every
 * Windows install does) without having Windows Hello enrolled.
 */
hello_gate_available: boolean, 
/**
 * Whether *this* vault currently requires the Windows Hello gate before
 * its platform-slot unlock. See `platform::hello`'s module doc for what
 * this does and does not cryptographically guarantee.
 */
hello_gate_enabled: boolean, };
