// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A named project can exist before it contains a secret. The name is stored
 * only inside an authenticated encrypted blob; the database sees an opaque
 * project list and cannot reveal repository or customer names while locked.
 */
export type VaultProject = { id: string, name: string, created_ms: number, };
