import js from "@eslint/js";
import eslintPluginPrettier from "eslint-plugin-prettier/recommended";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "**/dist",
      "**/target",
      "**/routeTree.gen.ts",
      "**/node_modules",
      // Generated by ts-rs (`cargo test --workspace export_bindings`) directly
      // from Rust -- linting/formatting output that gets overwritten on every
      // regeneration is pure noise; see packages/contract/index.ts's doc comment.
      "packages/contract/bindings/**",
    ],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-unused-vars": "off",

      // INV-010: Envryn makes no outbound network connection. The UI talks to
      // the Rust core over Tauri IPC and to nothing else. A `fetch` in the UI
      // is either a bug or an exfiltration path, and there is no legitimate
      // third case -- so it fails the build rather than a review.
      "no-restricted-globals": [
        "error",
        {
          name: "fetch",
          message:
            "The UI must not make network requests (INV-010). Use a Tauri IPC command in src-tauri instead.",
        },
        {
          name: "XMLHttpRequest",
          message: "The UI must not make network requests (INV-010). Use a Tauri IPC command.",
        },
        {
          name: "WebSocket",
          message: "The UI must not open sockets (INV-010). Sync lives in the Rust core.",
        },
        {
          name: "EventSource",
          message: "The UI must not open network streams (INV-010).",
        },
      ],

      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["@tanstack/react-start", "@tanstack/react-start/*"],
              message:
                "Envryn is a Tauri SPA, not a TanStack Start app. There is no server to run this on.",
            },
          ],
        },
      ],
    },
  },
  eslintPluginPrettier,
);
