/**
 * The generated IPC contract.
 *
 * Every type here is produced by `ts-rs` directly from the real Rust types
 * (`crates/envryn-core`, `src-tauri`) -- see `bindings/*.ts`, each of which
 * carries its own "Do not edit this file manually" header. Regenerate with:
 *
 *   cargo test --workspace export_bindings
 *
 * This file is the one hand-maintained piece: a plain barrel re-export so
 * `apps/ui/src/lib/ipc.ts` can import everything from `@envryn/contract`
 * instead of reaching into `bindings/` directly. Add a line here whenever a
 * new `#[ts(export)]` type is added on the Rust side.
 */

export type { SecretId } from "./bindings/SecretId";
export type { RustEnvironment } from "./bindings/RustEnvironment";
export type { SecretKind } from "./bindings/SecretKind";
export type { SecretPayload } from "./bindings/SecretPayload";
export type { CustomField } from "./bindings/CustomField";
export type { SecretRecord } from "./bindings/SecretRecord";
export type { SecretSummary } from "./bindings/SecretSummary";
export type { NewSecret } from "./bindings/NewSecret";
export type { SecretUpdate } from "./bindings/SecretUpdate";
export type { TrustedDevice } from "./bindings/TrustedDevice";
export type { Classification } from "./bindings/Classification";
export type { SearchFilter } from "./bindings/SearchFilter";


export type { ConflictSummary } from "./bindings/ConflictSummary";

export type { VaultStatus } from "./bindings/VaultStatus";
export type { VaultProject } from "./bindings/VaultProject";
export type { RestoreSummary } from "./bindings/RestoreSummary";
export type { AppSettings } from "./bindings/AppSettings";
export type { OwnIdentity } from "./bindings/OwnIdentity";
export type { DiscoveredPeer } from "./bindings/DiscoveredPeer";
export type { SyncSummary } from "./bindings/SyncSummary";
export type { PairingHostStarted } from "./bindings/PairingHostStarted";
export type { PairingSasReady } from "./bindings/PairingSasReady";
export type { PairingFailed } from "./bindings/PairingFailed";
export type { PairingComplete } from "./bindings/PairingComplete";
