/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MRouteRouteImport } from './routes/m/route'
import { Route as VaultRouteRouteImport } from './routes/vault/route'
import { Route as MIndexRouteImport } from './routes/m/index'
import { Route as MVaultRouteImport } from './routes/m/vault'
import { Route as VaultIndexRouteImport } from './routes/vault/index'
import { Route as VaultBackupRouteImport } from './routes/vault/backup'
import { Route as VaultDevicesRouteImport } from './routes/vault/devices'
import { Route as VaultSettingsRouteImport } from './routes/vault/settings'
import { Route as VaultSyncRouteImport } from './routes/vault/sync'
import { Route as MProjectsIndexRouteImport } from './routes/m/projects/index'
import { Route as MProjectsProjectIdRouteImport } from './routes/m/projects/$projectId'
import { Route as VaultCategoryCategoryIdRouteImport } from './routes/vault/category/$categoryId'
import { Route as VaultProjectsIndexRouteImport } from './routes/vault/projects/index'
import { Route as VaultProjectsProjectIdRouteImport } from './routes/vault/projects/$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MRouteRoute = MRouteRouteImport.update({
  id: '/m',
  path: '/m',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRouteRoute = VaultRouteRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const MIndexRoute = MIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MRouteRoute,
} as any)
const MVaultRoute = MVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => MRouteRoute,
} as any)
const VaultIndexRoute = VaultIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VaultRouteRoute,
} as any)
const VaultBackupRoute = VaultBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => VaultRouteRoute,
} as any)
const VaultDevicesRoute = VaultDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => VaultRouteRoute,
} as any)
const VaultSettingsRoute = VaultSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => VaultRouteRoute,
} as any)
const VaultSyncRoute = VaultSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => VaultRouteRoute,
} as any)
const MProjectsIndexRoute = MProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => MRouteRoute,
} as any)
const MProjectsProjectIdRoute = MProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => MRouteRoute,
} as any)
const VaultCategoryCategoryIdRoute = VaultCategoryCategoryIdRouteImport.update({
  id: '/category/$categoryId',
  path: '/category/$categoryId',
  getParentRoute: () => VaultRouteRoute,
} as any)
const VaultProjectsIndexRoute = VaultProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => VaultRouteRoute,
} as any)
const VaultProjectsProjectIdRoute = VaultProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => VaultRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/m': typeof MRouteRouteWithChildren
  '/vault': typeof VaultRouteRouteWithChildren
  '/m/vault': typeof MVaultRoute
  '/vault/backup': typeof VaultBackupRoute
  '/vault/devices': typeof VaultDevicesRoute
  '/vault/settings': typeof VaultSettingsRoute
  '/vault/sync': typeof VaultSyncRoute
  '/m/': typeof MIndexRoute
  '/vault/': typeof VaultIndexRoute
  '/m/projects/$projectId': typeof MProjectsProjectIdRoute
  '/vault/category/$categoryId': typeof VaultCategoryCategoryIdRoute
  '/vault/projects/$projectId': typeof VaultProjectsProjectIdRoute
  '/m/projects/': typeof MProjectsIndexRoute
  '/vault/projects/': typeof VaultProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/m/vault': typeof MVaultRoute
  '/vault/backup': typeof VaultBackupRoute
  '/vault/devices': typeof VaultDevicesRoute
  '/vault/settings': typeof VaultSettingsRoute
  '/vault/sync': typeof VaultSyncRoute
  '/m': typeof MIndexRoute
  '/vault': typeof VaultIndexRoute
  '/m/projects/$projectId': typeof MProjectsProjectIdRoute
  '/vault/category/$categoryId': typeof VaultCategoryCategoryIdRoute
  '/vault/projects/$projectId': typeof VaultProjectsProjectIdRoute
  '/m/projects': typeof MProjectsIndexRoute
  '/vault/projects': typeof VaultProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/m': typeof MRouteRouteWithChildren
  '/vault': typeof VaultRouteRouteWithChildren
  '/m/vault': typeof MVaultRoute
  '/vault/backup': typeof VaultBackupRoute
  '/vault/devices': typeof VaultDevicesRoute
  '/vault/settings': typeof VaultSettingsRoute
  '/vault/sync': typeof VaultSyncRoute
  '/m/': typeof MIndexRoute
  '/vault/': typeof VaultIndexRoute
  '/m/projects/$projectId': typeof MProjectsProjectIdRoute
  '/vault/category/$categoryId': typeof VaultCategoryCategoryIdRoute
  '/vault/projects/$projectId': typeof VaultProjectsProjectIdRoute
  '/m/projects/': typeof MProjectsIndexRoute
  '/vault/projects/': typeof VaultProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/m'
    | '/vault'
    | '/m/vault'
    | '/vault/backup'
    | '/vault/devices'
    | '/vault/settings'
    | '/vault/sync'
    | '/m/'
    | '/vault/'
    | '/m/projects/$projectId'
    | '/vault/category/$categoryId'
    | '/vault/projects/$projectId'
    | '/m/projects/'
    | '/vault/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/m/vault'
    | '/vault/backup'
    | '/vault/devices'
    | '/vault/settings'
    | '/vault/sync'
    | '/m'
    | '/vault'
    | '/m/projects/$projectId'
    | '/vault/category/$categoryId'
    | '/vault/projects/$projectId'
    | '/m/projects'
    | '/vault/projects'
  id:
    | '__root__'
    | '/'
    | '/m'
    | '/vault'
    | '/m/vault'
    | '/vault/backup'
    | '/vault/devices'
    | '/vault/settings'
    | '/vault/sync'
    | '/m/'
    | '/vault/'
    | '/m/projects/$projectId'
    | '/vault/category/$categoryId'
    | '/vault/projects/$projectId'
    | '/m/projects/'
    | '/vault/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MRouteRoute: typeof MRouteRouteWithChildren
  VaultRouteRoute: typeof VaultRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m': {
      id: '/m'
      path: '/m'
      fullPath: '/m'
      preLoaderRoute: typeof MRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/': {
      id: '/m/'
      path: '/'
      fullPath: '/m/'
      preLoaderRoute: typeof MIndexRouteImport
      parentRoute: typeof MRouteRoute
    }
    '/m/vault': {
      id: '/m/vault'
      path: '/vault'
      fullPath: '/m/vault'
      preLoaderRoute: typeof MVaultRouteImport
      parentRoute: typeof MRouteRoute
    }
    '/vault/': {
      id: '/vault/'
      path: '/'
      fullPath: '/vault/'
      preLoaderRoute: typeof VaultIndexRouteImport
      parentRoute: typeof VaultRouteRoute
    }
    '/vault/backup': {
      id: '/vault/backup'
      path: '/backup'
      fullPath: '/vault/backup'
      preLoaderRoute: typeof VaultBackupRouteImport
      parentRoute: typeof VaultRouteRoute
    }
    '/vault/devices': {
      id: '/vault/devices'
      path: '/devices'
      fullPath: '/vault/devices'
      preLoaderRoute: typeof VaultDevicesRouteImport
      parentRoute: typeof VaultRouteRoute
    }
    '/vault/settings': {
      id: '/vault/settings'
      path: '/settings'
      fullPath: '/vault/settings'
      preLoaderRoute: typeof VaultSettingsRouteImport
      parentRoute: typeof VaultRouteRoute
    }
    '/vault/sync': {
      id: '/vault/sync'
      path: '/sync'
      fullPath: '/vault/sync'
      preLoaderRoute: typeof VaultSyncRouteImport
      parentRoute: typeof VaultRouteRoute
    }
    '/m/projects/': {
      id: '/m/projects/'
      path: '/projects'
      fullPath: '/m/projects/'
      preLoaderRoute: typeof MProjectsIndexRouteImport
      parentRoute: typeof MRouteRoute
    }
    '/m/projects/$projectId': {
      id: '/m/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/m/projects/$projectId'
      preLoaderRoute: typeof MProjectsProjectIdRouteImport
      parentRoute: typeof MRouteRoute
    }
    '/vault/category/$categoryId': {
      id: '/vault/category/$categoryId'
      path: '/category/$categoryId'
      fullPath: '/vault/category/$categoryId'
      preLoaderRoute: typeof VaultCategoryCategoryIdRouteImport
      parentRoute: typeof VaultRouteRoute
    }
    '/vault/projects/': {
      id: '/vault/projects/'
      path: '/projects'
      fullPath: '/vault/projects/'
      preLoaderRoute: typeof VaultProjectsIndexRouteImport
      parentRoute: typeof VaultRouteRoute
    }
    '/vault/projects/$projectId': {
      id: '/vault/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/vault/projects/$projectId'
      preLoaderRoute: typeof VaultProjectsProjectIdRouteImport
      parentRoute: typeof VaultRouteRoute
    }
  }
}

interface MRouteRouteChildren {
  MVaultRoute: typeof MVaultRoute
  MIndexRoute: typeof MIndexRoute
  MProjectsProjectIdRoute: typeof MProjectsProjectIdRoute
  MProjectsIndexRoute: typeof MProjectsIndexRoute
}

const MRouteRouteChildren: MRouteRouteChildren = {
  MVaultRoute: MVaultRoute,
  MIndexRoute: MIndexRoute,
  MProjectsProjectIdRoute: MProjectsProjectIdRoute,
  MProjectsIndexRoute: MProjectsIndexRoute,
}

const MRouteRouteWithChildren =
  MRouteRoute._addFileChildren(MRouteRouteChildren)

interface VaultRouteRouteChildren {
  VaultBackupRoute: typeof VaultBackupRoute
  VaultDevicesRoute: typeof VaultDevicesRoute
  VaultSettingsRoute: typeof VaultSettingsRoute
  VaultSyncRoute: typeof VaultSyncRoute
  VaultIndexRoute: typeof VaultIndexRoute
  VaultCategoryCategoryIdRoute: typeof VaultCategoryCategoryIdRoute
  VaultProjectsProjectIdRoute: typeof VaultProjectsProjectIdRoute
  VaultProjectsIndexRoute: typeof VaultProjectsIndexRoute
}

const VaultRouteRouteChildren: VaultRouteRouteChildren = {
  VaultBackupRoute: VaultBackupRoute,
  VaultDevicesRoute: VaultDevicesRoute,
  VaultSettingsRoute: VaultSettingsRoute,
  VaultSyncRoute: VaultSyncRoute,
  VaultIndexRoute: VaultIndexRoute,
  VaultCategoryCategoryIdRoute: VaultCategoryCategoryIdRoute,
  VaultProjectsProjectIdRoute: VaultProjectsProjectIdRoute,
  VaultProjectsIndexRoute: VaultProjectsIndexRoute,
}

const VaultRouteRouteWithChildren = VaultRouteRoute._addFileChildren(
  VaultRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MRouteRoute: MRouteRouteWithChildren,
  VaultRouteRoute: VaultRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
